In [44]:
import pandas as pd

In [47]:
df = pd.read_csv("HAMOYE first assignment.csv", encoding= "latin-1")

In [50]:
df

Area Code      Area  Item Code           Item  Element Code  \
0              4   Algeria       2501     Population           511   
1              4   Algeria       2501     Population          5301   
2              4   Algeria       2901    Grand Total           664   
3              4   Algeria       2901    Grand Total           674   
4              4   Algeria       2901    Grand Total           684   
...          ...       ...        ...            ...           ...   
60938        181  Zimbabwe       2899  Miscellaneous          5142   
60939        181  Zimbabwe       2899  Miscellaneous           645   
60940        181  Zimbabwe       2899  Miscellaneous           664   
60941        181  Zimbabwe       2899  Miscellaneous           674   
60942        181  Zimbabwe       2899  Miscellaneous           684   

                                      Element             Unit     Y2014  \
0               Total Population - Both sexes     1000 persons  38924.00   
1                    Domestic supply quantity      1000 tonnes      0.00   
2               Food supply (kcal/capita/day)  kcal/capita/day   3377.00   
3      Protein supply quantity (g/capita/day)     g/capita/day     94.90   
4          Fat supply quantity (g/capita/day)     g/capita/day     80.06   
...                                       ...              ...       ...   
60938                                    Food      1000 tonnes     42.00   
60939     Food supply quantity (kg/capita/yr)               kg      3.06   
60940           Food supply (kcal/capita/day)  kcal/capita/day      3.00   
60941  Protein supply quantity (g/capita/day)     g/capita/day      0.10   
60942      Fat supply quantity (g/capita/day)     g/capita/day      0.04   

          Y2015     Y2016     Y2017     Y2018  
0      39728.00  40551.00  41389.00  42228.00  
1          0.00      0.00      0.00      0.00  
2       3379.00   3372.00   3341.00   3322.00  
3         94.35     94.72     92.82     91.83  
4         79.36     77.40     80.19     77.28  
...         ...       ...       ...       ...  
60938     46.00     33.00     19.00     16.00  
60939      3.33      2.35      1.33      1.08  
60940      4.00      3.00      1.00      1.00  
60941      0.11      0.08      0.04      0.04  
60942      0.05      0.03      0.02      0.01  

[60943 rows x 12 columns]

In [51]:
df.describe(include='all')

Area Code   Area     Item Code                     Item  \
count   60943.000000  60943  60943.000000                    60943   
unique           NaN     49           NaN                      119   
top              NaN  Kenya           NaN  Milk - Excluding Butter   
freq             NaN   1560           NaN                     1262   
mean      134.265576    NaN   2687.176706                      NaN   
std        72.605709    NaN    146.055739                      NaN   
min         4.000000    NaN   2501.000000                      NaN   
25%        74.000000    NaN   2562.000000                      NaN   
50%       136.000000    NaN   2630.000000                      NaN   
75%       195.000000    NaN   2775.000000                      NaN   
max       276.000000    NaN   2961.000000                      NaN   

        Element Code                   Element         Unit          Y2014  \
count   60943.000000                     60943        60943   59354.000000   
unique           NaN                        18            5            NaN   
top              NaN  Domestic supply quantity  1000 tonnes            NaN   
freq             NaN                      5295        40933            NaN   
mean     3814.856456                       NaN          NaN     134.196282   
std      2212.007033                       NaN          NaN    1567.663696   
min       511.000000                       NaN          NaN   -1796.000000   
25%       684.000000                       NaN          NaN       0.000000   
50%      5142.000000                       NaN          NaN       0.090000   
75%      5511.000000                       NaN          NaN       8.340000   
max      5911.000000                       NaN          NaN  176405.000000   

                Y2015          Y2016          Y2017          Y2018  
count    59395.000000   59408.000000   59437.000000   59507.000000  
unique            NaN            NaN            NaN            NaN  
top               NaN            NaN            NaN            NaN  
freq              NaN            NaN            NaN            NaN  
mean       135.235966     136.555222     140.917765     143.758381  
std       1603.403984    1640.007194    1671.862359    1710.782658  
min      -3161.000000   -3225.000000   -1582.000000   -3396.000000  
25%          0.000000       0.000000       0.000000       0.000000  
50%          0.080000       0.080000       0.100000       0.070000  
75%          8.460000       8.430000       9.000000       9.000000  
max     181137.000000  185960.000000  190873.000000  195875.000000

In [86]:
df.shape

(60943, 12)

In [55]:
df.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [88]:
#Percentage of missing data in 2014
(1589/59354)*100

2.6771573946153584

In [56]:
#minimum value of Element code
df['Element Code'].min()

511

In [91]:
#Getting the year that has the minimum value of Element code(511)
print(511 in df['Y2014'].values)
print(511 in df['Y2015'].values)
print(511 in df['Y2016'].values)
print(511 in df['Y2017'].values)

True
False
True
True


In [93]:
#groupby operation on Elements
df.groupby("Element")["Y2017"].sum()

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

In [99]:
i = [[35, 'Portugal', 94],[33, 'Argentina', 93], [30, 'Brazil', 92]]
col = ['Age', 'Nationality', 'Overall']
pd.DataFrame(i, columns= col, index = [1,2,3])

Age Nationality  Overall
1   35    Portugal       94
2   33   Argentina       93
3   30      Brazil       92

In [108]:
import numpy as np
array = np.array([[94,89,63],[93,92,48],[92,94,56]])
print(array[:1,1:])
print(array[1,:])
print(array[:2,1:])
print(array[:2,0:])

[[89 63]]
[93 92 48]
[[89 63]
 [92 48]]
[[94 89 63]
 [93 92 48]]


In [110]:
y = [(2,4),(7,8),(1,5,9)]
x = y[1][1]
x

8

In [111]:
df.groupby("Area")["Y2017"].sum()

Area
Algeria                         325644.27
Angola                          229159.57
Benin                           124771.22
Botswana                         22101.30
Burkina Faso                    101855.07
Cabo Verde                       14650.74
Cameroon                        232030.43
Central African Republic         29937.00
Chad                             71594.68
Comoros                             59.84
Congo                            41181.68
Côte d'Ivoire                   224599.01
Djibouti                         22729.91
Egypt                           866379.92
Eswatini                         54343.33
Ethiopia                        448683.76
Ethiopia PDR                         0.00
Gabon                            27979.64
Gambia                           23154.18
Ghana                           337599.06
Guinea                           98138.87
Guinea-Bissau                    19102.77
Kenya                           264660.66
Lesotho                      

In [66]:
df.groupby("Item")["Y2015"].sum()

Item
Alcohol, Non-Food        2180.00
Alcoholic Beverages     98783.72
Animal Products         11811.73
Animal fats            200675.72
Apples and products     10559.15
                         ...    
Vegetables, Other      158104.08
Vegetal Products       107064.17
Wheat and products     234710.51
Wine                     4251.81
Yams                   203151.78
Name: Y2015, Length: 119, dtype: float64

In [112]:
df.groupby("Item")["Y2018"].sum()

Item
Alcohol, Non-Food        2293.00
Alcoholic Beverages     97847.27
Animal Products         11578.61
Animal fats            269648.27
Apples and products      9640.51
                         ...    
Vegetables, Other      163987.21
Vegetal Products       107775.39
Wheat and products     242645.19
Wine                     4039.32
Yams                   221272.09
Name: Y2018, Length: 119, dtype: float64

In [67]:
#Unique countries
len(df['Area'].unique())

49

In [72]:
#Getting the index of Madagascar
df[df['Area'] == 'Madagascar'].index

Int64Index([30715, 30716, 30717, 30718, 30719, 30720, 30721, 30722, 30723,
            30724,
            ...
            32144, 32145, 32146, 32147, 32148, 32149, 32150, 32151, 32152,
            32153],
           dtype='int64', length=1439)

In [73]:
#df2 becomes data for Madagascar
df2 = df[30715:32153].reset_index()

In [74]:
df2

index  Area Code        Area  Item Code           Item  Element Code  \
0     30715        129  Madagascar       2501     Population           511   
1     30716        129  Madagascar       2501     Population          5301   
2     30717        129  Madagascar       2901    Grand Total           664   
3     30718        129  Madagascar       2901    Grand Total           674   
4     30719        129  Madagascar       2901    Grand Total           684   
...     ...        ...         ...        ...            ...           ...   
1433  32148        129  Madagascar       2899  Miscellaneous          5170   
1434  32149        129  Madagascar       2899  Miscellaneous          5142   
1435  32150        129  Madagascar       2899  Miscellaneous           645   
1436  32151        129  Madagascar       2899  Miscellaneous           664   
1437  32152        129  Madagascar       2899  Miscellaneous           674   

                                     Element             Unit     Y2014  \
0              Total Population - Both sexes     1000 persons  23590.00   
1                   Domestic supply quantity      1000 tonnes      0.00   
2              Food supply (kcal/capita/day)  kcal/capita/day   1986.00   
3     Protein supply quantity (g/capita/day)     g/capita/day     44.45   
4         Fat supply quantity (g/capita/day)     g/capita/day     22.18   
...                                      ...              ...       ...   
1433                               Residuals      1000 tonnes      0.00   
1434                                    Food      1000 tonnes     10.00   
1435     Food supply quantity (kg/capita/yr)               kg      0.44   
1436           Food supply (kcal/capita/day)  kcal/capita/day      0.00   
1437  Protein supply quantity (g/capita/day)     g/capita/day      0.01   

         Y2015     Y2016     Y2017     Y2018  
0     24234.00  24894.00  25571.00  26262.00  
1         0.00      0.00      0.00      0.00  
2      1922.00   1918.00   1943.00   1938.00  
3        43.26     43.35     43.94     44.17  
4        22.97     23.83     25.26     24.12  
...        ...       ...       ...       ...  
1433      0.00      0.00      0.00      0.00  
1434     11.00     11.00     11.00     12.00  
1435      0.44      0.44      0.44      0.44  
1436      0.00      0.00      0.00      0.00  
1437      0.01      0.01      0.01      0.01  

[1438 rows x 13 columns]

In [77]:
df2.groupby("Element")["Y2015"].sum()

Element
Domestic supply quantity                  31214.98
Export Quantity                             494.75
Fat supply quantity (g/capita/day)           91.84
Feed                                       2070.22
Food                                      21120.65
Food supply (kcal/capita/day)              7685.00
Food supply quantity (kg/capita/yr)         871.59
Import Quantity                            1721.80
Losses                                     2176.00
Other uses (non-food)                      3957.12
Processing                                 1803.00
Production                                29482.89
Protein supply quantity (g/capita/day)      173.05
Residuals                                  -616.00
Seed                                        699.00
Stock Variation                            -505.00
Total Population - Both sexes             24234.00
Name: Y2015, dtype: float64

In [113]:
S = [['him', 'sell'], [90, 28, 43]]
S[0][1][1]

'e'

In [79]:
df.shape

(60943, 12)

In [83]:
df.groupby("Area")["Y2017"].sum()

Area
Algeria                         325644.27
Angola                          229159.57
Benin                           124771.22
Botswana                         22101.30
Burkina Faso                    101855.07
Cabo Verde                       14650.74
Cameroon                        232030.43
Central African Republic         29937.00
Chad                             71594.68
Comoros                             59.84
Congo                            41181.68
Côte d'Ivoire                   224599.01
Djibouti                         22729.91
Egypt                           866379.92
Eswatini                         54343.33
Ethiopia                        448683.76
Ethiopia PDR                         0.00
Gabon                            27979.64
Gambia                           23154.18
Ghana                           337599.06
Guinea                           98138.87
Guinea-Bissau                    19102.77
Kenya                           264660.66
Lesotho                      

In [114]:
my_tuppy = (1,2,5,8)
my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment

In [115]:
df2.groupby("Element").sum()

index  Area Code  Item Code  \
Element                                                                 
Domestic supply quantity                3743186      15351     318888   
Export Quantity                         3272658      13416     279445   
Fat supply quantity (g/capita/day)      3460782      14190     296506   
Feed                                    1092115       4515      94030   
Food                                    3463065      14190     295817   
Food supply (kcal/capita/day)           3492713      14319     299405   
Food supply quantity (kg/capita/yr)     3463175      14190     295817   
Import Quantity                         3493699      14319     297945   
Losses                                  1723484       7095     148102   
Other uses (non-food)                   1606352       6579     138246   
Processing                              2379024       9804     201929   
Production                              3459797      14190     295071   
Protein supply quantity (g/capita/day)  3492824      14319     299405   
Residuals                               3296198      13545     280011   
Seed                                     652474       2709      56067   
Stock Variation                         3079112      12642     262174   
Total Population - Both sexes             30715        129       2501   

                                        Element Code     Y2014     Y2015  \
Element                                                                    
Domestic supply quantity                      630819  31578.76  31214.98   
Export Quantity                               614744    425.48    494.75   
Fat supply quantity (g/capita/day)             75240     88.71     91.84   
Feed                                          193235   2178.76   2070.22   
Food                                          565620  21405.42  21120.65   
Food supply (kcal/capita/day)                  73704   7945.00   7685.00   
Food supply quantity (kg/capita/yr)            70950    907.59    871.59   
Import Quantity                               622821   2010.71   1721.80   
Losses                                        281765   2252.00   2176.00   
Other uses (non-food)                         262854   4348.58   3957.12   
Processing                                    389956   1262.00   1803.00   
Production                                    606210  30337.51  29482.89   
Protein supply quantity (g/capita/day)         74814    177.79    173.05   
Residuals                                     542850   -603.00   -616.00   
Seed                                          116067    728.00    699.00   
Stock Variation                               497056    352.00   -505.00   
Total Population - Both sexes                    511  23590.00  24234.00   

                                           Y2016     Y2017     Y2018  
Element                                                               
Domestic supply quantity                31732.08  31927.87  32596.87  
Export Quantity                           535.06    566.81    535.81  
Fat supply quantity (g/capita/day)         95.32    101.02     96.42  
Feed                                     2121.40   2059.60   2133.60  
Food                                    21435.61  21676.21  22116.21  
Food supply (kcal/capita/day)            7669.00   7768.00   7748.00  
Food supply quantity (kg/capita/yr)       861.17    847.75    842.17  
Import Quantity                          1901.47   3139.79   3214.79  
Losses                                   2215.00   2153.00   2253.00  
Other uses (non-food)                    4114.08   4170.06   4221.06  
Processing                               1770.00   1826.00   1819.00  
Production                              29889.65  29267.86  30215.86  
Protein supply quantity (g/capita/day)    173.40    175.75    176.64  
Residuals                                -642.00   -657.00   -676.00  
Seed                                      720.00    695.00    728.00  
St